In [57]:
import math
import torch

def CE_1(predict, label): # input list, list
    loss = 0
    for i in range(len(predict)):
        loss += label[i]*math.log(predict[i])
    return -loss

def CE_2(predict, label_index): # input list, index
    return -math.log(predict[label_index])
    
def CE(predict, label): # input list, list
    return -math.log(predict[torch.argmax(label)])
    
# def FL(predict, label, gamma=2): #input list, list, float
#     pt = predict[torch.argmax(label)]
#     return ((1 - pt)**gamma * -math.log(pt)).item()
    
    
# predicts = Tensor, label = Tensor, loss = float
predict = torch.tensor([0.05, 0.9, 0.05])
label = torch.tensor([0, 1, 0])
label_index = 1

print(CE_1(predict, label))
print(CE_2(predict, label_index))
print(CE(predict, label))
                 
# print(FL(predict, label))

tensor(0.1054)
0.10536054214877988
0.10536054214877988
0.0010536059271544218


In [94]:
import torch.nn as nn
import torch.nn.functional as F

ls = [[1,3,2,4],
      [3,8,4,6]]
label = [3,1]

ls_tensor = torch.Tensor(ls)
label_tensor = torch.tensor(label, dtype=torch.long)
criterion = nn.CrossEntropyLoss()

print(ls_tensor)
print(label_tensor)
# tensor([[1., 3., 2., 4.],
#         [3., 8., 4., 6.]])
# tensor([2, 1])

def CEE(predict, label):
    delta = 1e-7
    predict_sm = torch.softmax(predict, dim=1)
    label = F.one_hot(label, num_classes=len(predict[0]))
    return torch.mean((label * -torch.log(predict_sm + delta)).sum(dim=1))

def CEE2(predict, label): # LogSoftmax + NLLLoss
    predict_log = nn.LogSoftmax(dim=1)(predict)
    return nn.NLLLoss()(predict_log, label)
    
# 1.2945
print(CEE(ls_tensor, label_tensor))
print(CEE2(ls_tensor, label_tensor))
print(criterion(ls_tensor, label_tensor))

tensor([[1., 3., 2., 4.],
        [3., 8., 4., 6.]])
tensor([3, 1])
tensor(0.2945)
tensor(0.2945)
tensor(0.2945)


In [95]:
ls = [[1,3,2,4],
      [3,8,4,6]]
label = [3,1]

ls_tensor = torch.Tensor(ls)
label_tensor = torch.tensor(label, dtype=torch.long)

def FL(predict, label, alpha=1., gamma=2.0):
    predict_sm = torch.softmax(predict, dim=1)
    label = F.one_hot(label, num_classes=len(predict[0]))
    factor = alpha * (1-predict_sm)**gamma
    return torch.mean((factor * (label * -torch.log(predict_sm))).sum(dim=1))

print(FL(ls_tensor, label_tensor))

tensor(0.0293)


In [64]:
import torch.nn as nn

ls = [[1,3,2,4],
      [3,8,4,6]]
label = [2,1]

ls_tensor = torch.Tensor(ls)
label_tensor = torch.tensor(label, dtype=torch.long)

print(ls_tensor)
print(label_tensor)

criterion = nn.CrossEntropyLoss()
loss = criterion(ls_tensor, label_tensor)
print(loss)

##############################################################

ls = [[1,3,2,4]]
label = [3]

ls_tensor = torch.Tensor(ls)
label_tensor = torch.tensor(label, dtype=torch.long)

loss1 = criterion(ls_tensor, label_tensor)
print(loss1)

##############################################################

ls = [[3,8,4,6]]
label = [1]

ls_tensor = torch.Tensor(ls)
label_tensor = torch.tensor(label, dtype=torch.long)

criterion = nn.CrossEntropyLoss()
loss2 = criterion(ls_tensor, label_tensor)
print(loss2)

print((loss1 + loss2))

tensor([[1., 3., 2., 4.],
        [3., 8., 4., 6.]])
tensor([2, 1])
tensor(1.2945)
tensor(0.4402)
tensor(0.1488)
tensor(0.5889)


In [65]:
t = torch.randint(0,9, (5,))
print(t)

a = torch.zeros((5,10))
a[range(5), t] = 1
print(a)

tensor([2, 3, 1, 1, 0])
tensor([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
